name: GO application 1

on:
  push:
    branches: [ githubaction ]
  pull_request:
    branches: [ githubaction ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2.1.4
    - name: Run CloudDefense to check for vulnerabilities
      uses: cdefense/actions/go@master
      with:
        project-name: GO_Github_Action_Test_1
        api-key: ${{ secrets.PROD_API_KEY }}
